"use client";
import { useEffect, useRef, useState } from "react";
import type { CreateMealInput, MealType, PlannedMeal } from "@/lib/meal-types";
import { Button, Input } from "./ui";
export function MealDialog({ date, mealType, item, onClose, onSave }: { date: string; mealType: MealType; item?: PlannedMeal; onClose: () => void; onSave: (input: CreateMealInput) => Promise<void> }) {
  const [name, setName] = useState(item?.displayName ?? ""); const [notes, setNotes] = useState(item?.notes ?? ""); const [servings, setServings] = useState(item?.servings ?? 4); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const ref = useRef<HTMLInputElement>(null);
  useEffect(() => { ref.current?.focus(); const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()}; window.addEventListener("keydown",esc); return()=>window.removeEventListener("keydown",esc); },[onClose]);
  async function submit(e: React.FormEvent){e.preventDefault(); if(!name.trim()){setError("Meal name is required.");return;} setBusy(true);setError("");try{await onSave({mealDate:date,mealType,displayName:name.trim(),notes:notes.trim()||null,servings})}catch(x){setError(x instanceof Error?x.message:"Could not save meal.")}finally{setBusy(false)}}
  return <div role="dialog" aria-modal="true" aria-labelledby="meal-title" className="fixed inset-0 z-50 grid place-items-end bg-black/35 p-4 sm:place-items-center"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-5 shadow-xl"><h2 id="meal-title" className="text-xl font-black">{item?"Edit meal":"Add meal"}</h2><p className="mt-1 text-sm text-[#68766f]">{date} · {mealType.toLowerCase()}</p><label className="mt-4 block text-sm font-bold">Meal name<Input ref={ref} value={name} onChange={e=>setName(e.target.value)} /></label><label className="mt-3 block text-sm font-bold">Notes<Input value={notes} onChange={e=>setNotes(e.target.value)} /></label><label className="mt-3 block text-sm font-bold">Servings<Input type="number" min={1} max={50} value={servings} onChange={e=>setServings(Number(e.target.value))} /></label>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><Button type="button" onClick={onClose} className="flex-1 !bg-white !text-[#203a2e] border">Cancel</Button><Button disabled={busy} className="flex-1">{busy?"Saving...":"Save"}</Button></div></form></div>;
}
