"use client";
import { useState } from "react";
import type { CreateHouseholdInput, Diet } from "@/lib/onboarding-types";
import { Button, Input } from "./ui";
const diets:Diet[]=["No restrictions","Vegetarian","Vegan","Gluten-free","Dairy-free","Low carb"];
export function OnboardingWizard({onComplete}:{onComplete:(input:CreateHouseholdInput)=>Promise<void>}){
 const [step,setStep]=useState(1);const [name,setName]=useState("");const [size,setSize]=useState("1");const [budget,setBudget]=useState("");const [diet,setDiet]=useState<Diet>("No restrictions");const [timeZone,setTimeZone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Indiana/Indianapolis");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function finish(){setBusy(true);setError("");try{await onComplete({name:name.trim(),householdSize:Number(size),weeklyBudget:budget?Number(budget):null,dietaryPreference:diet,locale:navigator.language||"en-US",timeZone})}catch(e){setError(e instanceof Error?e.message:"Unable to create household.")}finally{setBusy(false)}}
 return <section aria-labelledby="onboarding-title"><p className="text-xs font-black uppercase tracking-[.18em] text-[#486957]">Step {step} of 4</p><h1 id="onboarding-title" className="mt-2 text-3xl font-black">Set up PantryPilot</h1>{error&&<p role="alert" className="mt-4 rounded-2xl bg-[#fff1e6] p-4 text-[#8b432e]">{error}</p>}
 {step===1&&<label className="mt-6 block font-bold">Household name<Input autoFocus value={name} onChange={e=>setName(e.target.value)} className="mt-2" placeholder="Biela Household"/></label>}
 {step===2&&<div className="mt-6 space-y-4"><label className="block font-bold">Household size<Input type="number" min="1" max="50" value={size} onChange={e=>setSize(e.target.value)} className="mt-2"/></label><label className="block font-bold">Weekly grocery budget<Input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} className="mt-2" placeholder="200"/></label></div>}
 {step===3&&<div className="mt-6"><label className="block font-bold">Dietary preference<select className="mt-2 min-h-11 w-full rounded-2xl border bg-white px-3" value={diet} onChange={e=>setDiet(e.target.value as Diet)}>{diets.map(value=><option key={value}>{value}</option>)}</select></label><label className="mt-4 block font-bold">Time zone<Input value={timeZone} onChange={e=>setTimeZone(e.target.value)} className="mt-2"/></label></div>}
 {step===4&&<div className="mt-6 rounded-3xl border bg-white p-5"><h2 className="font-black">Review</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="font-bold">Household</dt><dd>{name}</dd></div><div><dt className="font-bold">People</dt><dd>{size}</dd></div><div><dt className="font-bold">Budget</dt><dd>{budget?`$${budget}`:"Not set"}</dd></div><div><dt className="font-bold">Diet</dt><dd>{diet}</dd></div></dl></div>}
 <div className="mt-7 grid grid-cols-2 gap-3">{step>1?<Button type="button" className="border bg-white text-[#203a2e]" onClick={()=>setStep(step-1)}>Back</Button>:<span/>}{step<4?<Button disabled={step===1&&!name.trim()} onClick={()=>setStep(step+1)}>Continue</Button>:<Button disabled={busy||!name.trim()} onClick={()=>void finish()}>{busy?"Creating...":"Create household"}</Button>}</div></section>
}
