"use client";
import { useCallback, useEffect, useMemo, useState } from "react"; import { LogOut, Pencil, Plus, Search, Trash2, Wheat } from "lucide-react"; import { api, ApiError } from "@/lib/api"; import type { Bootstrap, CreatePantryInput, PantryItem } from "@/lib/types"; import { publicEnv } from "@/lib/env"; import { Button, Input } from "./ui"; import { ErrorState, InlineAlert, Loading } from "./status"; import { PantryDialog } from "./pantry-dialog"; import { DeleteDialog } from "./delete-dialog";
export function PantryPilotApp(){const [status,setStatus]=useState<"loading"|"ready"|"error"|"signedout">("loading");const [data,setData]=useState<Bootstrap|null>(null);const [error,setError]=useState<unknown>(null);const [notice,setNotice]=useState<{message:string;correlationId?:string}|null>(null);const [query,setQuery]=useState("");const [dialog,setDialog]=useState<{mode:"create"|"edit";item?:PantryItem}|null>(null);const [deleting,setDeleting]=useState<PantryItem|null>(null);const [busyDelete,setBusyDelete]=useState(false);
 const load=useCallback(async()=>{setStatus("loading");setError(null);try{const session=await api.session();if(!session.user){setStatus("error");setError(new ApiError(401,"AUTHENTICATION_REQUIRED","Development sign-in is unavailable."));return}const b=await api.bootstrap();setData(b);setStatus("ready")}catch(e){setError(e);setStatus("error")}},[]);useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);
 const householdId=data?.activeHouseholdId;const filtered=useMemo(()=>data?.pantry.filter(i=>i.name.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);
 async function refreshPantry(){if(!householdId)return;const pantry=await api.listPantry(householdId);setData(d=>d?{...d,pantry}:d)}
 async function save(input:CreatePantryInput){if(!householdId)throw new Error("No active household.");try{if(dialog?.mode==="edit"&&dialog.item){const updated=await api.updatePantry(householdId,dialog.item.id,{...input,version:dialog.item.version});setData(d=>d?{...d,pantry:d.pantry.map(x=>x.id===updated.id?updated:x)}:d)}else{const created=await api.createPantry(householdId,input);setData(d=>d?{...d,pantry:[...d.pantry,created]}:d)}setDialog(null)}catch(e){if(e instanceof ApiError&&e.status===409){await refreshPantry();setDialog(null);setNotice({message:"This item changed in another session. PantryPilot refreshed the latest server version.",correlationId:e.correlationId});return}throw e}}
 async function remove(){if(!householdId||!deleting)return;setBusyDelete(true);try{await api.deletePantry(householdId,deleting.id,deleting.version);setData(d=>d?{...d,pantry:d.pantry.filter(x=>x.id!==deleting.id)}:d);setDeleting(null)}catch(e){if(e instanceof ApiError&&e.status===409){await refreshPantry();setDeleting(null);setNotice({message:"This item changed before deletion. PantryPilot refreshed the latest server version.",correlationId:e.correlationId})}else setNotice({message:e instanceof Error?e.message:"Unable to delete item.",correlationId:e instanceof ApiError?e.correlationId:undefined})}finally{setBusyDelete(false)}}
 async function signOut(){try{await api.signOut()}finally{setData(null);setStatus("signedout")}}
 if(status==="loading")return <Shell><Loading label="Loading your pantry"/></Shell>;if(status==="error")return <Shell><ErrorState error={error} retry={load}/></Shell>;if(status==="signedout")return <Shell><div className="mx-auto max-w-md rounded-3xl border bg-white p-6 text-center"><h1 className="text-2xl font-black">Signed out</h1><p className="mt-2 text-sm text-[#6d7d74]">Development authentication remains available only in local mode.</p><Button onClick={load} className="mt-4">Sign in locally</Button></div></Shell>;if(!data)return null;
 return <Shell><header className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#486957]">{data.households[0]?.name??"PantryPilot"}</p><h1 className="mt-1 text-4xl font-black">Your pantry</h1><p className="mt-2 text-sm text-[#6d7d74]">Server-synced inventory Â· {data.user.displayName??data.user.email}</p></div><button aria-label="Sign out" onClick={signOut} className="rounded-xl border bg-white p-3"><LogOut size={18}/></button></header>{notice&&<div className="mt-4"><InlineAlert message={notice.message} correlationId={notice.correlationId} onDismiss={()=>setNotice(null)}/></div>}<div className="mt-5 flex gap-2"><label className="relative flex-1"><span className="sr-only">Search pantry</span><Search className="absolute left-3 top-3 text-[#6d7d74]" size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pantry" className="pl-10"/></label><Button onClick={()=>setDialog({mode:"create"})} aria-label="Add pantry item"><Plus size={18}/></Button></div><main className="mt-5">{filtered.length===0?<div className="rounded-3xl border bg-white p-8 text-center"><Wheat className="mx-auto text-[#486957]" size={38}/><h2 className="mt-3 text-xl font-black">{data.pantry.length?"No matching items":"Your pantry is empty"}</h2><p className="mt-2 text-sm text-[#6d7d74]">{data.pantry.length?"Try another search.":"Add the first item to begin tracking inventory."}</p></div>:<ul className="space-y-3" aria-label="Pantry items">{filtered.map(item=><li key={item.id} className="flex items-center gap-3 rounded-3xl border bg-white p-4 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf5db]"><Wheat size={20}/></span><div className="min-w-0 flex-1"><h2 className="truncate font-black">{item.name}</h2><p className="text-sm text-[#6d7d74]">{String(item.quantity)} {item.unit}{item.category?` Â· ${item.category}`:""}</p><p className="text-xs text-[#84918a]">Version {item.version}</p></div><button aria-label={`Edit ${item.name}`} onClick={()=>setDialog({mode:"edit",item})} className="rounded-xl border p-2"><Pencil size={17}/></button><button aria-label={`Delete ${item.name}`} onClick={()=>setDeleting(item)} className="rounded-xl border p-2 text-[#9a4f36]"><Trash2 size={17}/></button></li>)}</ul>}</main><footer className="mt-6 text-center text-xs text-[#7c8982]">API {publicEnv.apiBaseUrl} Â· App {publicEnv.appVersion}</footer>{dialog&&<PantryDialog mode={dialog.mode} item={dialog.item} onClose={()=>setDialog(null)} onSubmit={save}/>} {deleting&&<DeleteDialog item={deleting} busy={busyDelete} onCancel={()=>setDeleting(null)} onConfirm={remove}/>}</Shell>}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen p-3 sm:p-8"><div className="mx-auto min-h-[760px] max-w-lg rounded-[2.5rem] border-[6px] border-[#203a2e] bg-[#faf8f1] p-5 shadow-2xl sm:p-7">{children}</div></div>}

